project:
  type: website

website:
  title: "quarto"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "Menu"  
        menu:
          - text: "Heading 1"
          - text: "Page A"
            href: page-a.html
          - text: "Page B"
            href: page-b.html
          - text: "---------"
          - text: "Heading 2"
          - text: "Page C"
            href: page-c.html
          - text: "Page D"
            href: page-d.html   
    right:
      - text: "About"
        href: about.html
      - icon: fa-question fa-lg
        href: https://example.com
format:
  html:
    # theme: cosmo
    css: styles.css
    toc: true

editor: visual

